build:
    environment:
        php:
            version: 7.1,7.2
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --whitelist src/ --coverage-clover=coverage --bootstrap vendor/autoload.php tests/CacheTest.php'
                coverage:
                    file: 'coverage'
                    format: 'clover'